export const stopNames: { [key: string]: string } = {
  "The Point": "Iosta na Rinne",
  "Spencer Dock": "Duga Spencer",
  "Mayor Square - NCI": "Cearnóg an Mhéara — CNÉ",
  "George's Dock": "Duga Sheoirse",
  "Connolly": "Conghaile",
  "Busáras": "Busáras",
  "Abbey Street": "Sráid na Mainistreach",
  "Jervis": "Jervis",
  "Four Courts": "Na Ceithre Cúirteanna",
  "Smithfield": "Margadh na Feirme",
  "Museum": "Músaem",
  "Heuston": "Heuston",
  "James's": "Ospidéal San Séamas",
  "Fatima": "Fatima",
  "Rialto": "Rialto",
  "Suir Road": "Bóthar na Siúire",
  "Goldenbridge": "An Droichead Órga",
  "Drimnagh": "Droimeanach",
  "Fettercairn": "Fothair Chardain",
  "Cheeverstown": "Baile an tSíbhrigh",
  "Citywest Campus": "Campas Gnó Iarthar na Cathrach",
  "Fortunestown": "Baile Uí Fhoirtcheirn",
  "Saggart": "Teach Sagard",
  "Broombridge": "Droichead Broome",
  "Cabra": "Cabrach",
  "Phibsborough": "Baile Phib",
  "Grangegorman": "Gráinseach Ghormáin",
  "Broadstone - University": "An Chloch Leathan — ITBhÁC",
  "Dominick": "Doiminic",
  "Parnell": "Parnell",
  "O'Connell - Upper": "Ó Conaill Uachtarach",
  "O'Connell - GPO": "Ó Conaill - AOP",
  "Marlborough": "Maoilbhríde",
  "Westmoreland": "Westmoreland",
  "Trinity": "An Trionóid",
  "Dawson": "Dásain",
  "St. Stephen's Green": "Faiche Stiabhna",
  "Harcourt": "Sráid Fhearchair",
  "Charlemont": "Charlemont",
  "Ranelagh": "Raghnallach",
  "Beechwood": "Coill na Feá",
  "Cowper": "Cowper",
  "Milltown": "Baile an Mhuilinn",
  "Windy Arbour": "Na Glasáin",
  "Dundrum": "Dún Droma",
  "Balally": "Baile Amhlaoibh",
  "Kilmacud": "Cill Mochuda",
  "Stillorgan": "Stigh Lorgan",
  "Sandyford": "Áth an Ghainimh",
  "Central Park": "An Pháirc Láir",
  "Glencairn": "Gleann an Chairn",
  "The Gallops": "An Eachrais",
  "Leopardstown Valley": "Gleann Baile na Lobhair",
  "Ballyogan Wood": "Coill Bhaile Uí Ógáin",
  "Racecourse": "RCC",
  "Carrickmines": "Carraig Mhaighin",
  "Brennanstown": "BRE",
  "Laughanstown": "Baile an Lachnáin",
  "Cherrywood": "Coill na Sílíní",
  "Brides Glen": "Gleann Bhríde",
  "Blackhorse": "An Capall Dubh",
  "Bluebell": "An Cloigín Gorm",
  "Kylemore": "An Chill Mhór",
  "Red Cow": "An Bhó Dhearg",
  "Kingswood": "Coill an Rí",
  "Belgard": "Belgard",
  "Cookstown": "Baile an Chócaigh",
  "Hospital": "Ospidéal Tamhlachta",
  "Tallaght": "Tamhlacht"
};
